apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: s-top-qa
patches:
- path: domain.json
  target:
    kind: Ingress
    name: fe-ingress
images:
- name: scgskku/stop-fe
  newName: scgskku/stop-fe-qa
  newTag: 9567238235f3ddf2bcc2eaa063f6974117318b43
- name: scgskku/stop-fe-qa
  newTag: fb2151c48db2c9ed16c54ca2a68d7604c324ca6e-22852177792-1
resources:
- ../../../base/fe
