apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: s-top
bases:
- ../../../base/be
resources:
  - namespace.yaml
  - secret.yaml

patches:
  - path: domain.json
    target:
      kind: Ingress
      name: Ingress
images:
- name: registry.scg.skku.ac.kr/cs-grad-thesis-be
  newTag: prod0
