apiVersion: v1
kind: Secret
metadata:
  name: stop-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: <path:kv/data/stop-secret#datasource | base64encode>
  SPRING_DATASOURCE_USERNAME: <path:kv/data/stop-secret#user | base64encode>
  SPRING_DATAASOURCE_PASSWORD: <path:kv/data/stop-secret#password | base64encode>
  
