apiVersion: v1
kind: Secret
metadata:
  name: stop-secret
type: Opaque
data:
  DATASOURCE: <path:kv/data/stop-secret#datasource | base64encode>
  USER: <path:kv/data/stop-secret#user | base64encode>
  PASSWORD: <path:kv/data/stop-secret#password | base64encode>
  
