apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: s-top-prod
resources:
- ../../../base/fe

patches:
- path: domain.json
  target:
    kind: Ingress
    name: fe-ingress
images:
- name: scgskku/stop-fe
  newName: scgskku/stop-fe-prod
  newTag: df69d72b003398a55dbc3817aee1b5e8f5c04d43
- name: scgskku/stop-fe-prod
  newTag: d3beba6e42ea184410e32f1f9b2c7315d306cbf9-22749302575-2
